# Generated by Django 3.1.7 on 2021-03-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'android_metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=200)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=200, unique=True)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogIeltsstories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'catalog_ieltsstories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('change_message', models.TextField()),
                ('action_flag', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=200)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gmat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('favorite', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gmat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grammars',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('menuid', models.IntegerField(blank=True, null=True)),
                ('favorite', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'grammars',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gramuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gramuse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('sentence', models.TextField(blank=True, null=True)),
                ('favorite', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Idioms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('favorite', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Idioms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ielts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('favorite', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ielts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ieltsessay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'IELTSEssay',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ieltstest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sublevel', models.IntegerField(blank=True, db_column='SubLevel', null=True)),
                ('qnumber', models.IntegerField(blank=True, db_column='QNumber', null=True)),
                ('qcontent', models.TextField(blank=True, db_column='QContent', null=True)),
                ('answera', models.TextField(blank=True, db_column='AnswerA', null=True)),
                ('answerb', models.TextField(blank=True, db_column='AnswerB', null=True)),
                ('answerc', models.TextField(blank=True, db_column='AnswerC', null=True)),
                ('answerd', models.TextField(blank=True, db_column='AnswerD', null=True)),
                ('correctanswer', models.TextField(blank=True, db_column='CorrectAnswer', null=True)),
                ('passed', models.IntegerField(blank=True, db_column='Passed', null=True)),
            ],
            options={
                'db_table': 'IELTSTest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ieltswords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('example', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'IELTSWords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iverbsfull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseform', models.CharField(blank=True, max_length=200, null=True)),
                ('pastsimple', models.CharField(blank=True, max_length=200, null=True)),
                ('pastpart', models.CharField(blank=True, max_length=200, null=True)),
                ('person3rd', models.CharField(blank=True, max_length=200, null=True)),
                ('gerund', models.CharField(blank=True, max_length=200, null=True)),
                ('definition', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'IVerbsFull',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('audio', models.CharField(blank=True, max_length=200, null=True)),
                ('favorite', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'lessons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('audio', models.CharField(blank=True, max_length=200, null=True)),
                ('favorite', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Listening',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mostcategories',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'MostCategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mostphrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.IntegerField(blank=True, db_column='catID', null=True)),
                ('phrase', models.CharField(blank=True, max_length=200, null=True)),
                ('audio', models.CharField(blank=True, max_length=200, null=True)),
                ('favorite', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'MostPhrases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mostwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.IntegerField(blank=True, db_column='catID', null=True)),
                ('word', models.CharField(blank=True, max_length=200, null=True)),
                ('audio', models.CharField(blank=True, max_length=200, null=True)),
                ('favorite', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'MostWords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phrasalverb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('favorite', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'PhrasalVerb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pronun',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('audio', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'pronun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PronunDetail',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('catid', models.IntegerField(blank=True, db_column='catID', null=True)),
                ('seq', models.IntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('audio', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'pronun_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proverbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('favorite', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Proverbs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('catid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'rules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('favorite', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Sat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Slangs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('definition', models.CharField(blank=True, max_length=200, null=True)),
                ('example', models.CharField(blank=True, max_length=200, null=True)),
                ('etymology', models.CharField(blank=True, max_length=200, null=True)),
                ('synonyms', models.CharField(blank=True, max_length=200, null=True)),
                ('favorite', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Slangs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Tenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topicidioms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('example', models.CharField(blank=True, max_length=200, null=True)),
                ('subcate', models.CharField(blank=True, db_column='subCate', max_length=200, null=True)),
                ('favorite', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'TopicIdioms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topicphrases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicid', models.IntegerField(blank=True, db_column='TopicId', null=True)),
                ('explaination', models.TextField(blank=True, null=True)),
                ('sentence', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TopicPhrases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('favorite', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Topics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Verbs',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('favorite', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Verbs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vocabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate1', models.CharField(blank=True, max_length=200, null=True)),
                ('cate2', models.CharField(blank=True, max_length=200, null=True)),
                ('word', models.CharField(blank=True, max_length=200, null=True)),
                ('meaning', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('favorite', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vocabs',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ieltsstories',
            options={'managed': False},
        ),
    ]
