# Generated by Django 3.1.7 on 2021-04-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210329_1431'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ieltsstories',
            table='ieltsstories',
        ),
        migrations.AlterModelTable(
            name='ieltstest',
            table='ieltstest',
        ),
    ]
