# Generated by Django 3.1.7 on 2021-04-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210403_1345'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Idioms',
        ),
        migrations.DeleteModel(
            name='Ieltsessay',
        ),
        migrations.DeleteModel(
            name='Ieltswords',
        ),
        migrations.DeleteModel(
            name='Iverbsfull',
        ),
        migrations.DeleteModel(
            name='Listening',
        ),
        migrations.DeleteModel(
            name='Mostcategories',
        ),
        migrations.DeleteModel(
            name='Mostphrases',
        ),
        migrations.DeleteModel(
            name='Mostwords',
        ),
        migrations.DeleteModel(
            name='Phrasalverb',
        ),
        migrations.DeleteModel(
            name='Proverbs',
        ),
        migrations.DeleteModel(
            name='Sat',
        ),
        migrations.DeleteModel(
            name='Slangs',
        ),
        migrations.DeleteModel(
            name='Tenses',
        ),
        migrations.DeleteModel(
            name='Topicidioms',
        ),
        migrations.DeleteModel(
            name='Topicphrases',
        ),
        migrations.DeleteModel(
            name='Topics',
        ),
        migrations.DeleteModel(
            name='Verbs',
        ),
    ]
