# Generated by Django 3.1.7 on 2021-04-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210403_2242'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ieltsstories',
            table='IELTSStories',
        ),
        migrations.AlterModelTable(
            name='ieltstest',
            table='IELTSTest',
        ),
    ]
